name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      env:
        IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.repository }}:latest
      run: |
        docker build -t ${IMAGE_NAME} .

    - name: Export Docker image to tar archive
      if: ${{ github.event_name == 'pull_request' }}
      env:
        IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.repository }}:latest
      run: |
        docker image save --output=image.tar ${IMAGE_NAME}

    - name: Upload Docker image tar archive
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'pull_request' }}
      with:
        name: go-web-cicd-docker
        path: image.tar

    - name: Log in to GHCR
      uses: docker/login-action@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to GHCR
      if: ${{ github.event_name != 'pull_request' }}
      env:
        IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.repository }}:latest
      run: |
        docker push ${IMAGE_NAME}
