name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  GO_VERSION: '1.24.2'

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build binary
      run: |
        go build -o bin/go-web-cicd ./cmd/web

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        TAG_IMAGE="${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}"
        LATEST_IMAGE="${{ env.REGISTRY }}/${{ github.repository }}:latest"
        docker build -t ${TAG_IMAGE} .
        docker image tag ${TAG_IMAGE} ${LATEST_IMAGE}
        docker push ${TAG_IMAGE}
        docker push ${LATEST_IMAGE}

    - name: Create release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${GITHUB_REF_NAME} \
          --generate-notes \
          --notes "\`docker pull ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}\`" \
          ./bin/go-web-cicd
